# Generated by Django 5.2.6 on 2025-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
