# Generated by Django 5.2.6 on 2025-09-30 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_idea_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="idea",
            name="likes",
        ),
        migrations.AddField(
            model_name="idea",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
