# Generated by Django 5.2.6 on 2025-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="画像"
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/", verbose_name="動画"
            ),
        ),
    ]
